// Common
import useAuth from 'hooks/useAuth'
import Head from 'next/head'
// Components

const HomePage = () => {

    const { user } = useAuth()

    return (
        <>
            <Head>
                <title>👋🏻 Welcome { user?.user }</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='mt-20'>
                <div className='flex flex-col justify-center items-center'>
                    <h1 className='text-lg font-semibold mb-4'>Next.js boilerplate</h1>
                        <h1>👋🏻 Welcome { user?.user }</h1>
                </div>
            </div>
        </>
    )
}

HomePage.protected = true

export default HomePage