// Common
import Head from 'next/head'
// Components
import AuthForm from '@components/root/AuthForm'

const RootPage = () => {
    return (
        <>
            <Head>
                <title>NextJS Boilerplate 🚀</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='mt-20'>
                <div className='flex flex-col justify-center items-center'>
                    <h1 className='text-lg font-semibold mb-4'>Next.js boilerplate</h1>
                    <AuthForm />
                </div>
            </div>
        </>
    )
}

export async function getStaticProps(context) {
    return {
        props: {}, // will be passed to the page component as props
    }
}

export default RootPage